modLoader = "javafml"
loaderVersion = "${neoforge_loader_version_range}"
license = "MIT"
issueTrackerURL = "https://github.com/UltrusBot/glow-banners/issues"

[[mods]]
modId = "glowingbanners"
version = "${version}"
displayName = "Glow Banners"
displayURL = "https://www.ultrusmods.me/"
logoFile = "glowingbanners.png"
logoBlur = false
credits = "MerchantPug"
authors = "UltrusBot"
description = '''This mod adds glowing banners'''

[[mixins]]
config = "glowingbanners.mixins.json"

[[accessTransformers]]
file="glowingbanners.cfg"

[[dependencies.glowingbanners]]
modId = "neoforge"
type = "required"
versionRange = "${neoforge_loader_version_range}"
ordering = "NONE"
side = "BOTH"

[[dependencies.glowingbanners]]
modId = "minecraft"
type = "required"
versionRange = "${minecraft_version_range}"
ordering = "NONE"
side = "BOTH"